"""Readable report and all-layer atlas from verified offline analysis outputs."""
from pathlib import Path
import json,csv,itertools,shutil
from html import escape as E

ROOT=Path('/Users/mohammed.awad/Documents/Codex/2026-09-19/c');OUT=ROOT/'outputs/ph_analysis'
read=lambda p:json.loads((OUT/p).read_text())
rows=read('layer_metrics.json');selections=read('selections.json');phases=read('phase_summaries.json')
comp=read('comparisons/summary.json');extra=read('additional_checks.json')
h0=read('h0_groups/all_layers_h0_groups.json')['layers'];h0map={(r['model'],r['layer']):r for r in h0}
names={'crystal':'Crystal','starcoderbase-3b':'StarCoderBase-3B','openllama-3b':'OpenLLaMA-3B'}
models=list(names);rowmap={(r['model'],r['layer']):r for r in rows}
def fmt(x,n=3):return f'{x:,.{n}f}'
def percent(x,n=1):return f'{100*x:.{n}f}%'
def link(path,text):return f'<a href="{E(path)}">{E(text)}</a>'
def table(head,body):return '<div class="table-wrap"><table><thead><tr>'+''.join('<th>'+E(s)+'</th>' for s in head)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+str(c)+'</td>' for c in r)+'</tr>' for r in body)+'</tbody></table></div>'
def figure(path,caption):return f'<figure><a href="{E(path)}"><img loading="lazy" src="{E(path)}" alt="{E(caption)}"></a><figcaption>{E(caption)} Click to enlarge.</figcaption></figure>'
sections=[]
def section(id,title,body):sections.append(f'<section id="{id}"><h2>{E(title)}</h2>{body}</section>')

section('start','What we found', '''<p class="lead">The three models share a broad change with depth: typical loop lifetimes get shorter relative to the cloud’s overall distance scale, while late connectivity becomes strongly associated with leading digits. But their best numerical-ordering layers do <strong>not</strong> share one distinctive topological signature.</p>
<div class="cards"><article><span class="tag">Most useful similarity</span><h3>Crystal and StarCoder’s final profiles are close</h3><p>Their final layers are the closest pair of H1 loop-count curves among all 1,152 Crystal–StarCoder layer pairs. This remains a strong similarity after removing total-persistence differences, but not under every diagram comparison.</p></article>
<article><span class="tag">Most useful distinction</span><h3>Best numerical ordering is a different stage</h3><p>Crystal L7 and OpenLLaMA L8 show very little leading-digit component separation, even at their best threshold. Their late layers show much stronger separation. StarCoder is already partly separated at its best-rho layer, L21.</p></article>
<article><span class="tag">Important correction</span><h3>Long H0 bars often describe outliers</h3><p>In every contextual layer, the final merge attaches a group of at most nine targets. It should not be interpreted as two large populations staying separated.</p></article></div>
<p><strong>Reading guide:</strong> H0 describes separate groups and when they connect. H1 describes loops that appear and disappear as the connection distance grows. A loop’s “lifetime” is a range of distances, not elapsed time. Rho measures how well a PCA coordinate orders the numbers. Explained variance measures how much of the cloud’s variation a projection preserves. A Betti curve counts the features present at each distance. Unless stated otherwise, distances are divided by each layer’s typical pair distance so we can compare clouds of different sizes.</p>
<p><strong>Scope:</strong> 94 contextual layers, 10,000 points each, 1,692,308 saved H1 intervals; all 4,371 layer pairs compared with full-support H0/H1 Betti curves. Three embedding levels are treated separately. The previously missing StarCoder embedding H1 was resolved by an exact five-vector duplicate quotient, so all 97 levels now have results available.</p>
<p class="note">These are descriptive findings for these checkpoints, this prompt format and one context per number. They are not proof of a donut, a universal number manifold, statistical significance, or a causal tokenization effect. No new inference or Modal compute was used for this analysis.</p>''')

anchor=[]
for m in models:
 r=rowmap[(m,selections[m]['best_rho_pc1'])];g=h0map[(m,r['layer'])]
 anchor.append([names[m],f'L{r["layer"]} ({percent(r["depth"])})',fmt(r['rho_pc1'],4),percent(r['ev_pc12'],2),f'{r["h1_count"]:,}',fmt(r['h1_max'],4),fmt(r['h1_median'],4),fmt(g['maximum_lead_ari'],4)])
section('rho','1. Do the best-rho layers have the same topology?', '<p><strong>What we checked:</strong> each model’s highest PC1 rank correlation, with its complete H0/H1 diagram and all-scale component membership.</p>'+table(['Model','Selected level','PC1 rho','2D variance','H1 intervals','Longest H1','Median H1','Best leading-digit ARI'],anchor)+'''
<p><strong>What we found:</strong> Crystal and StarCoder have almost identical longest lifetimes (about 0.156), but Crystal has 24,712 intervals versus StarCoder’s 14,239, and nearly twice the typical lifetime. A single maximum would hide that difference. Their H1 Betti-curve distance is 0.06775—larger than about 84% of their cross-model layer-pair distances. OpenLLaMA’s selected layer is different again.</p>
<p>Leading-digit component agreement is very low for Crystal L7 (ARI 0.0331) and OpenLLaMA L8 (0.0252), but substantial for StarCoder L21 (0.7835). All three have high PCA numerical ordering, so there is no single associated connectivity pattern. Their peak depths also differ: 21.9%, 58.3%, and 30.8% through the networks.</p>
<p><strong>Useful?</strong> Yes. This does not support the simple hypothesis that “best rho” automatically selects the same topological regime. It does not rule out shared numerical mechanisms. ARI is chance-adjusted partition agreement: 1 is perfect agreement; about 0 is its random-partition baseline. The reported maximum is selected over distance thresholds, so it is exploratory.</p>'''+figure('figures/anchor_comparisons.png','Selected layers: complete H1 lifetime distributions, H1 Betti curves and H0 Betti curves. Curve panels show normalized distances 0–2; full-support comparisons use every event.'))

ev=[]
for m in models:
 r=rowmap[(m,1)];s=selections[m];p2=rowmap[(m,s['best_rho_pc2'])]
 ev.append([names[m],f'L1 · {percent(r["ev_pc12"],2)}',fmt(r['rho_pc1'],4),f'L{s["best_ev_pc1"]}',f'L{p2["layer"]} · {fmt(p2["rho_pc2"],4)}'])
section('variance','2. Does the best explained variance reveal a common shape?', '<p><strong>What we checked:</strong> highest two-PC variance, highest PC1 variance and highest PC2 rho, keeping these definitions separate.</p>'+table(['Model','Best PC1+PC2 variance','PC1 rho there','Best PC1 variance layer','Best PC2 rho'],ev)+'''
<p><strong>What we found:</strong> all three two-PC variance peaks occur at L1, but their PH differs. OpenLLaMA L1 versus Crystal L1 has an H1 curve distance near the 95th percentile of that model pair; OpenLLaMA versus StarCoder is near the 97th percentile. Higher means less similar. StarCoder L1 has a particularly clear five-component plateau exactly matching digit lengths: 1–9, 10–99, 100–999, 1000–9999 and 10000, over normalized radius 1.05046–1.54418.</p>
<p>Crystal’s highest PC1 variance is instead its final level, L32. Final returned levels include an extra normalization operation, so this peak cannot be attributed solely to the last transformer block. Switching to best PC2 rho selects L9, L9 and L25; their H1 curve distances are 0.06028, 0.06920 and 0.07786, again giving no common signature.</p>
<p><strong>Useful?</strong> Useful for separating projection quality from numerical and topological properties. Explained variance alone is not a good selector for a shared numerical topology.</p>''')

trend=[]
for m in models:
 early=next(x for x in phases if x['model']==m and x['group']=='early');late=next(x for x in phases if x['model']==m and x['group']=='late')
 r=rowmap[(m,selections[m]['final'])]
 trend.append([names[m],fmt(early['h1_median'],5),fmt(late['h1_median'],5),percent(1-late['h1_median']/early['h1_median']),f'{r["h1_count"]:,}',fmt(r['h1_max'],4)])
section('depth','3. What changes with depth?', '<p><strong>What we checked:</strong> every layer, relative-depth anchors, early/middle/late thirds, adjacent changes, and the last three/five layers.</p>'+table(['Model','Early-third typical lifetime','Late-third typical lifetime','Reduction','Final H1 intervals','Final longest lifetime'],trend)+'''
<p>“Typical lifetime” here is the median across layers of each layer’s median H1 lifetime. All lifetimes are divided by that layer’s saved median pair distance.</p>
<p><strong>What we found:</strong> typical lifetimes decline in all three models, and the late stages contain fewer H1 intervals than their early maxima. This is a broad trend, not a monotonic rule for every adjacent layer. The longest normalized H1 lifetime occurs at <strong>L2 in all three models</strong>, rather than at best rho or the final layer. OpenLLaMA’s longest bars rise again in part of the late network even while its median lifetime stays low.</p>
<p>The largest H1 curve changes occur at Crystal L3→L4, StarCoder L1→L2 and OpenLLaMA L2→L3. OpenLLaMA’s L15→L16 change is its second largest. These are descriptive transitions, not statistically inferred change points. Middle and late stages still contain model-specific changes.</p>
<p><strong>Useful?</strong> Yes. There is a shared relative-scale trend, while the timing and exceptional loops differ. Fewer/shorter bars do not on their own mean better numerical ability or a simpler uniquely identified manifold.</p>'''+figure('figures/depth_profiles.png','All 94 contextual layers. Relative depth is layer number divided by the final transformer layer. Black-outlined dots mark best PC1-rho selections.'))

final=[]
for m in models:
 g=h0map[(m,selections[m]['final'])];a=g['all_threshold_maxima']['leading_digit'];details=sorted(a['component_details'],key=lambda x:x['size'],reverse=True)[:9];count=sum(x['size'] for x in details);purity=sum(max(x['leading_digit_counts']) for x in details)/count
 final.append([names[m],fmt(g['maximum_lead_ari'],4),f'{count:,}/10,000',percent(purity,3),fmt(a['threshold_bands']['0.8']['total_width'],5)])
section('groups','4. Are leading-digit groups real connectivity structures?', '<p><strong>What we checked:</strong> every distinct H0 merge threshold using the saved exact minimum spanning trees. These trees recover the connected components of the complete distance graph at every threshold; this is not a calculation on the k=4 graph. Components were formed from distances, then compared to digit labels.</p>'+table(['Final model','Maximum leading-digit ARI','Targets in nine largest components','Leading-digit purity of those cores','Radius width with ARI ≥ 0.8'],final)+'''
<p><strong>What we found:</strong> all three develop leading-digit-associated components. Crystal and StarCoder have broader separation intervals and cover almost all targets in nine pure cores. OpenLLaMA’s separation is weaker and occupies a narrower distance range. All residual small components remain in the analysis.</p>
<p>The first layer to exceed a best-over-radius ARI of 0.8 is Crystal L26/32, StarCoder L22/36 and OpenLLaMA L19/26. The value 0.8 is a descriptive reference, not a significance threshold. The exact best threshold is label-selected; the width shows whether the high agreement is narrow or sustained.</p>
<p><strong>Why this is more useful than color alone:</strong> a perfect numeric k=4 line already has 99.4975% same-leading-digit neighbors. Late hidden neighborhoods also have far larger numeric jumps and many same-leading-digit connections across digit lengths. Final mean numeric gaps are 181.25, 228.10 and 444.42, versus 1.50 for the numeric-line baseline. Together with H0 membership, this supports a digit-associated organization under this prompt, but not a causal tokenizer explanation.</p>
<p><strong>A trap we found:</strong> forcing exactly nine total components gives almost zero digit agreement in every layer. By that late threshold, the main groups have merged and only outliers remain. The nine meaningful large groups occur earlier, alongside residual small components.</p>'''+figure('h0_groups/h0_structure_by_depth.png','Exact H0 connectivity across all thresholds and layers; label agreement is evaluated after distance-based component construction.'))

finaldist=[]
for r in comp['selected_comparisons']:
 if r['selection']=='final':finaldist.append([r['a']+' ↔ '+r['b'],fmt(r['h1'],6),f'{r["h1_cross_pair_percentile"]:.2f}%',fmt(r['h0'],6)])
section('similarity','5. Which models actually look alike topologically?', '<p><strong>What we checked:</strong> 4,371 pairs of layers, using the exact area between full H0/H1 Betti curves; secondary landscape summaries; and selected bottleneck distances with certified bounds. H0 and H1 are kept separate.</p>'+table(['Final-layer pair','H1 curve distance','Percentile within that model pair','H0 curve distance'],finaldist)+'''
<p><strong>What we found:</strong> Crystal L32–StarCoder L36 is the closest H1 curve pair among all 1,152 Crystal–StarCoder combinations. The final-five-layer cross-model median is 0.00801, compared with 0.02494 for Crystal–OpenLLaMA and 0.02641 for StarCoder–OpenLLaMA. Thus this is not solely a one-layer coincidence.</p>
<p>After scaling each H1 curve to unit area, the final Crystal–StarCoder pair remains among the closest 1.56% of their pairs. It therefore shares a similar distance-scale profile, not just low total persistence.</p>
<p><strong>But the answer depends on the feature being compared.</strong> The bottleneck distance focuses on the hardest individual feature to match. For final layers it ranks Crystal–OpenLLaMA closest (0.04594–0.04639), then Crystal–StarCoder (0.06513), then StarCoder–OpenLLaMA (0.07573). So “Crystal and StarCoder have the same topology” would be too strong; “their final H1 count profiles are especially similar” is supported.</p>
<p><strong>A small bottleneck value needs a baseline.</strong> This comparison can discard a feature by matching it to the diagram’s diagonal. Discarding every feature provides a simple upper bound, equal to half the longest lifetime across the two diagrams. At best-rho layers, Crystal–StarCoder reaches 99.89% of that bound and Crystal–OpenLLaMA reaches 100%. At final layers, StarCoder–OpenLLaMA also reaches 100%; Crystal–StarCoder reaches 86.0%, and Crystal–OpenLLaMA 75.73–76.47%. A value near this bound provides little evidence that the strongest loops correspond between models, even if the absolute number looks small.</p>
<p>Depth matching also helps descriptively: cross-model H1 curve-distance median is 0.02905 for depths within five percentage points, versus 0.04235 across all cross-model pairs. Same numbered layers give 0.02881. These differently selected comparison sets do not establish that either alignment is uniquely correct.</p>
<p><strong>Useful?</strong> Yes, especially because the alternative comparisons prevent an overly broad claim. Percentiles here describe this collection of layers; they are not p-values.</p>'''+figure('comparisons/all_layer_similarity.png','Pairwise similarity over all contextual layers. Read the metric labels; a small summary distance does not prove identical shapes or identical numerical labels.'))

section('misleading','6. Which measurements were limited or misleading?', '''<div class="cards"><article><h3>The final H0 merge</h3><p>All 94 final merges attach at most nine points. At final layers, the last detached targets are Crystal 213, StarCoder 1288 and OpenLLaMA 1223. It is an outlier diagnostic here, not a good summary of bulk separation.</p></article>
<article><h3>A “dominant loop” from one long bar</h3><p>The longest bar accounts for less than 0.12% of total H1 lifetime in every layer; the plotted top 30 account for only 0.45–1.98%. This does not invalidate those bars, but screenshots of 30 bars omit nearly all interval mass. The longest/second-longest ratio ranges from 1.0003 to 2.0516, with no consistent isolated-loop pattern.</p></article>
<article><h3>Persistence entropy</h3><p>Normalized entropy is uniformly high, 0.9601–0.9693. It adds little discrimination compared with lifetime distributions, connectivity membership and curve distances. A large rank correlation on this narrow range is not a large practical effect.</p></article></div>
<p>For example, across layers, median H1 lifetime and leading-digit neighbor fraction are strongly anticorrelated in StarCoder (−0.925) and OpenLLaMA (−0.927). But correlations between their adjacent changes are only −0.103 and −0.201. Much of the shared trend can track depth; this is not evidence that one property causes the other. Longest-lifetime versus PC1-rho correlations also differ: Crystal +0.021, StarCoder +0.224, OpenLLaMA −0.608.</p>
<p><strong>Scale matters enormously:</strong> raw longest lifetime increases with depth (rank correlations +0.920, +0.964, +0.975), while normalized longest lifetime decreases (−0.722, −0.476, −0.355). Both statements are true: the clouds expand while loops become smaller relative to typical interpoint distance. “Loops get smaller” without specifying units would be misleading.</p>'''+figure('figures/associations.png','Descriptive associations across dependent layers. First-difference sensitivity and all values are saved in associations.csv; no significance tests or independence assumptions are used.'))

checks=[
('Best PC1 rho','L7/L21/L8 differ in interval distributions and component membership; similar longest lifetime for Crystal/StarCoder hides large differences.','Useful: no common best-rho signature established.','rho'),
('Best PC2 rho','L9/L9/L25; H1 curve distances 0.06028, 0.06920, 0.07786. It selects different stages from PC1.','Useful secondary selector, not an aligned numerical axis.','variance'),
('Best two-PC variance','L1 for all; OpenLLaMA’s H1 profile is far from the other two in pairwise ranks.','Projection concentration does not imply common PH.','variance'),
('Best PC1 variance','Crystal L32 versus L1 in the other models; mixes final-normalized and early states.','Limited as a cross-model stage selector.','variance'),
('Matched relative depth','Six anchors checked; all cross-pairs within ±0.05 depth have median H1 distance 0.02905 versus 0.04235 overall.','Useful descriptive alignment, not evidence of identical processing stages.','similarity'),
('Early/middle/late thirds','Late-third median lifetimes are 43.5%, 52.3%, 43.9% below early-third values.','Clear shared normalized-scale trend; not strictly monotone.','depth'),
('Last three and five levels','Crystal–StarCoder final-five H1 median 0.00801 versus 0.02494/0.02641 for pairs involving OpenLLaMA.','Similarity persists across a window.','similarity'),
('Neighborhoods of peaks','±2-layer PC1-rho ranges: Crystal .809–.898, StarCoder .824–.929, OpenLLaMA .581–.840; topology ranges saved.','Peaks vary in local stability; avoid single-layer stories.','data'),
('Same numbered layers','84 cross-model pairs; median H1 distance 0.02881. Not a controlled superiority test against relative depth.','Secondary comparison; network depths differ.','similarity'),
('H0 merge-distance distribution','Exact 9,999 finite merges per contextual layer and component memberships examined.','More informative with group sizes than scalar maxima.','groups'),
('H0 plateaus and long separation','StarCoder L1 is exactly digit-length split; 90/94 widest interior plateaus already contain ≥9,900 points in one giant component.','Distinguishes real bulk groups from outliers.','groups'),
('Longest H1 lifetime','All three normalized maxima occur at L2, not at best rho.','Useful exceptional-feature diagnostic; not a measure of numerical quality.','depth'),
('Complete H1 lifetime spectrum','1,692,308 bars used; typical normalized persistence decreases broadly with depth.','Useful beyond the displayed longest 30.','depth'),
('Dominance and lifetime gaps','Longest/second ratio 1.0003–2.0516; no universal isolated dominant loop.','Does not justify a circle/donut label.','misleading'),
('Counts at persistence cutoffs','Thresholds .01/.02/.05/.1/.2 checked. Final counts above .05: 92/71/147; above .1: 0/3/7; above .2: all zero.','Counts depend strongly on cutoff; these are not significance thresholds.','data'),
('Birth/death scales','All birth/death arrays and per-layer first birth, peak scale, last death are retained; model atlases show scale shifts.','Useful localization in distance scale, not localization to target numbers.','atlas'),
('Betti curves','Exact event-based curves compared over full support, with tie handling.','Strong comparison summary; different diagrams can share a curve.','similarity'),
('Total persistence','Full sum of lifetimes verified equal to exact area under H1 Betti curve; unit-area sensitivity keeps final Crystal–StarCoder close.','Useful mass summary; redundant with curve area.','similarity'),
('Persistence entropy','Only 0.9601–0.9693 across all contextual layers.','Limited discrimination in this dataset.','misleading'),
('Diagram distances','Selected full-diagram bottleneck values certified by matching bounds/witnesses; final pair ordering differs from count curves.','Important cross-check against broad shape claims.','similarity'),
('Persistence landscapes','Top five landscape levels on a common grid, all bars competing; finer-grid selected-pair sensitivity checked.','Useful secondary summary; higher landscape levels omitted.','methods'),
('Adjacent-layer changes','Largest H1 curve transitions: Crystal 3→4, StarCoder 1→2, OpenLLaMA 2→3.','Candidate transitions, not causal or statistical change points.','depth'),
('Cross-model convergence','Final Crystal–StarCoder count profiles are especially close, while OpenLLaMA differs; strongest-bar metric gives another ranking.','Property-specific convergence, not universal shared topology.','similarity'),
('Associations with rho/variance','Longest H1 versus PC1-rho correlations: +.021/+.224/−.608. No uniform relationship; first differences included.','Useful negative result; layers are dependent observations.','misleading'),
('Numerical neighbors and digit labels','Late H0 components align with leading digits; numerical gaps remain much larger than the true number-line baseline.','Strong descriptive label association, no causal tokenization conclusion.','groups'),
('Raw versus normalized scale','Raw lifetimes grow while normalized ones shrink; saved median distances span factors ~142/190/512 within models.','Essential: unit choice reverses the apparent trend.','misleading')]
section('checks','7. All 26 planned checks: result and usefulness', '<p>Every planned comparison on the saved data was computed. The checks are correlated views of the same experiment, not 26 independent confirmations. Related downloads include '+link('additional_checks.json','secondary anchors, peak windows, cutoffs and scale sensitivity')+'.</p>'+table(['#','What we examined','What we found','Usefulness'],[[i+1,link('#'+anchor,title),finding,use] for i,(title,finding,use,anchor) in enumerate(checks)]))

atlas=[]
for r in rows:
 m=r['model'];l=r['layer'];g=h0map[(m,l)];prior=rowmap.get((m,l-1));badges=[]
 for key,label in [('best_rho_pc1','best PC1 rho'),('best_rho_pc2','best PC2 rho'),('best_ev_pc12','best 2D variance'),('best_ev_pc1','best PC1 variance'),('final','final')]:
  if selections[m][key]==l:badges.append(label)
 change='First contextual level; no contextual predecessor.' if prior is None else f'Compared with L{l-1}, H1 interval count changes by {r["h1_count"]-prior["h1_count"]:+,}; median normalized lifetime changes by {100*(r["h1_median"]/prior["h1_median"]-1):+.1f}%.'
 desc=(f'We examined every saved H0/H1 interval and all H0 merge thresholds. This layer has {r["h1_count"]:,} H1 intervals; median lifetime {r["h1_median"]:.5f}, longest {r["h1_max"]:.5f}, and longest/second ratio {r["h1_top_ratio"]:.3f}. '
       f'The longest interval is born at {r["h1_top_birth"]:.5f} and dies at {r["h1_top_death"]:.5f}. Peak simultaneous H1 count is {r["h1_peak_betti"]:,} at radius {r["h1_peak_scale"]:.5f}. '
       f'There are {r["h1_count_gt_0.05"]:,} lifetimes above 0.05 and {r["h1_count_gt_0.1"]:,} above 0.1; these cutoffs are descriptive. '+change)
 url=f'../ph_fullrange_overnight/results/results/{m}/layer_{l:02d}/persistence.png'
 atlas.append(f'<details class="layer" data-model="{m}" data-search="{E(names[m].lower()+" layer "+str(l)+" "+" ".join(badges))}"><summary>{E(names[m])} · Layer {l} <span class="badges">{E(" · ".join(badges))}</span><small>PC1 rho {r["rho_pc1"]:.3f} · H1 median {r["h1_median"]:.4f} · digit ARI {g["maximum_lead_ari"]:.3f}</small></summary><p>{desc}</p><p><strong>Connectivity:</strong> highest leading-digit ARI {g["maximum_lead_ari"]:.4f}; highest digit-length ARI {g["maximum_digits_ari"]:.4f}, each at its own optimized radius. Median numerical gap across MST edges: {g["mst_numeric_jump_median"]:g}. Full connection occurs at radius {r["h0_connect"]:.5f}; its last merge concerns a tiny group.</p><p><strong>Projection:</strong> PC1 rho {r["rho_pc1"]:.4f}; PC2 rho {r["rho_pc2"]:.4f}; PC1+PC2 variance {percent(r["ev_pc12"],2)}. Neither is a complete description of hidden-space geometry.</p><p><strong>Usefulness:</strong> compare this layer’s typical persistence, component membership and adjacent changes; a large bar count or one long bar cannot identify a unique shape.</p>{figure(url,names[m]+" L"+str(l)+": original saved PH figure; barcode panel shows only the 30 longest H1 bars, while the analysis uses all intervals.")}</details>')
section('atlas','8. Every contextual layer: individual observations', '<p>Each record follows the same rubric. Search by model, “layer 7”, “best”, or “final”; click a row to see its observations and original figure. All distances below are normalized by that layer’s median pair distance.</p><div class="filters"><label>Model <select id="model"><option value="all">All three models</option>'+''.join(f'<option value="{m}">{E(n)}</option>' for m,n in names.items())+'</select></label><label>Find <input id="search" type="search" placeholder="e.g. best PC1 rho"></label><span id="visible">94 layers</span></div>'+''.join(atlas)+'<h3>Complete H1 diagram atlases</h3><p>These are birth/death plots, not pictures of the original point clouds. Their diagonal bands do not mean the hidden vectors form a line.</p>'+''.join(figure(f'figures/{m}_all_diagrams.png',f'{names[m]}: every contextual H1 diagram with shared axes within the model. All intervals are plotted.') for m in models))

section('embedding','9. Embedding levels and the resolved missing result', '''<p>Crystal and OpenLLaMA L0 are identical final-“=” token vectors across all targets, so their H0 collapses at zero and they have no H1 loops. These are architectural/extraction baselines, not evidence that the models lack numerical knowledge.</p>
<p><strong>StarCoder L0 is now resolved:</strong> all 10,000 vectors were checked bitwise and contain exactly five distinct vectors, one for each prompt token length. The original duplicate-heavy GPU attempt timed out. A separate exact zero-distance quotient computation gives <strong>zero H1 bars</strong>. Ripser and giotto-ph agree; independent F2 boundary ranks give zero H1 at every threshold; all four positive H0 merge distances equal the archived full-point H0 distances. The original 9,995 zero deaths and one essential component are preserved.</p>
<p>This is an exact reduction of duplicate metric points, not approximate subsampling. It used no cloud job and does not replace the historical failed-run record. The old cloud record remains 96/97; including this validated supplement, all 97 levels are available. Its normalization uses the archived diameter fallback because the sampled median distance is zero.</p>
<p>Its 99.34% two-PC variance describes learned position structure before contextual processing. It should not be selected as evidence of exceptionally strong numerical representation.</p>'''+figure('audit/star_embedding_supplement/persistence.png','Supplementary StarCoder embedding-level PH, computed through exact duplicate reduction and checked against archived H0.')+'<p>'+link('audit/star_embedding_supplement/PROOF_AND_SCOPE.md','Exact reduction proof and scope')+' · '+link('audit/star_embedding_supplement/validation.json','Validation record')+'</p>')

section('limits','10. What this does not settle', '''<p><strong>We cannot label the data “a donut” or “a cup.”</strong> H0/H1 give connectivity and loop information across distance scales. A torus surface has two independent H1 directions and an H2 class; a solid torus is a different object. We did not compute H2. Even matching these counts would not uniquely identify a shape. No H1 would not prove a line either: trees and filled regions can also lack H1.</p>
<p>The H1 figures plot feature birth and death, not number coordinates. Eventual one-component/no-loop behavior is inevitable for a full finite Rips filtration and is not evidence of a number line. A long-lived bar deserves investigation but is not automatically significant; a tiny bar is not automatically meaningless.</p>
<p><strong>Important experimental limits:</strong> the vectors are at the final “=” before answer generation, not isolated numeral embeddings. Each target has a different random context, with only one context per target. Digit count perfectly determines prompt token length and extraction position. Four-digit targets comprise 90% of the cloud; 10000 is the only five-digit target. The next correct output token is the leading digit, so late grouping is compatible with preparing that output. This is a plausible explanation, not a causal test.</p>
<p>Crystal inference used bfloat16; the other models used float32. All stored arrays being float32 does not remove that difference. Final returned layers include LayerNorm/RMSNorm. Architecture, training, dimension, tokenizer and precision vary together; this study does not reproduce the paper’s controlled tokenization experiment.</p>
<p><strong>Not answered by the saved diagrams:</strong> which numbers form a particular H1 loop; whether loops lie within or between digit groups; pointwise local topology; replication under new prompt contexts; comparison to a properly matched geometric null; causal numerical behavior. These require additional experiments or saved cycle/cocycle representatives. Global diagrams cannot be retroactively divided into group-specific H1 diagrams.</p>
<p><strong>Most valuable follow-ups, in order:</strong> repeated and crossed prompt contexts; controlled length/position and alternative next-output tasks; representative cycles/cocycles for selected stable features; matched geometric nulls and perturbation checks; then group/local PH or selected H2 if those specific questions remain motivated. These follow-ups were not run as part of this saved-data analysis.</p>''')

section('methods','11. Methods and reliability', '''<p>The main analysis uses all 10,000 targets at each of the 94 contextual layers. H0 comes from float64 direct-difference Euclidean MSTs. Saved H1 is full-range Vietoris–Rips over F2 with float32 filtration, without kNN restriction or PCA projection. Each layer’s birth/death scale is divided by the saved median of 100,000 seeded off-diagonal pair draws.</p>
<p><strong>H0:</strong> every distinct MST threshold is scanned, including tied edges together. Component-label agreement uses adjusted Rand index. Maxima over radii are exploratory; high-agreement widths and component coverage are reported alongside them.</p>
<p><strong>H1:</strong> all intervals contribute to spectra, entropy, cutoff counts and event-based Betti curves. The infinite H0 bar is excluded from finite-lifetime summaries and cancels between curves. Exact Betti L1 distance integrates the absolute count difference and divides counts by 10,000; it is a pseudometric on diagrams because different interval pairings can share a curve.</p>
<p><strong>Landscapes:</strong> the top five levels are evaluated on a common 1,025-point grid, with all bars competing for those levels. Selected comparisons were checked on 4,097 points; differences were below 0.000005. Higher landscape levels are omitted, so this is not full-landscape equality.</p>
<p><strong>Bottleneck:</strong> selected retained-bar matchings are extended by matching omitted bars to the diagonal, giving a full-diagram upper bound. Nearest-match witnesses against every opposite-diagram bar and triangle bounds give lower bounds. Seven of the nine primary pairs have matching lower/upper values to numerical tolerance; two retain explicitly reported intervals. No truncated result is silently called full exact matching.</p>
<p><strong>Validation:</strong> input artifact hashes, canonical target IDs, scalar summaries, normalized arrays and H0 tree structure were checked. Betti event-tie tests and the equality of lifetime sum to curve area passed. An independent analysis reproduced all 94 rows’ totals, entropy, longest lifetimes, cutoff counts and H0 summaries. Original PH synthetic/backend gates were reviewed. Only 16 of 1,692,308 contextual H1 lifetimes fall at or below the recorded filtration-rounding sensitivity bound; this bound is not a statistical noise threshold and does not cover inference precision or prompt uncertainty.</p>
<p>Associations are descriptive Spearman correlations; adjacent differences provide a sensitivity check to shared depth trends. No p-values are reported, and layers are not treated as independent repeats. Model-pair percentiles and radius-optimized label scores are exploratory. The same-numbered and relative-depth comparison sets differ and should not be treated as a randomized comparison.</p>
<p>Primary references: <a href="https://jmlr.org/papers/v16/bubenik15a.html">Bubenik: persistence landscapes</a>; <a href="https://arxiv.org/abs/1303.7117">Fasy et al.: confidence sets for persistence diagrams</a>; <a href="https://gudhi.inria.fr/python/latest/bottleneck_distance_user.html">GUDHI: bottleneck distance</a>; <a href="https://ripser.scikit-tda.org/en/latest/notebooks/Representative%20Cocycles.html">Ripser: representative cocycles</a>; <a href="https://pi.math.cornell.edu/~hatcher/AT/AT.pdf">Hatcher: algebraic topology</a>.</p>''')

downloads=[('layer_metrics.csv','All 94 layers: scalar measurements'),('associations.csv','Across-layer and adjacent-change associations'),('phase_summaries.json','Early/middle/late and final windows'),('additional_checks.json','Secondary selections, peak windows and scale/cutoff sensitivity'),('comparisons/pairs.csv','All 4,371 layer-pair comparisons'),('comparisons/selected_bottleneck.csv','Certified bottleneck values and bounds'),('comparisons/COMPARISON_FINDINGS.md','Detailed similarity findings'),('h0_groups/H0_FINDINGS.md','Detailed connectivity findings'),('h0_groups/all_layers_h0_groups.json','Full component membership summaries'),('audit/SCIENTIFIC_AUDIT.md','Experiment and interpretation audit'),('validation.json','Main validation record'),('input_hashes.json','Source fingerprints'),('audit/star_embedding_supplement/validation.json','Resolved embedding-level validation')]
section('data','12. Results, figures and reproducibility','<p>All analysis is local and the original experiment artifacts remain unchanged. Files are retained for follow-up work.</p><ul>'+''.join('<li>'+link(p,t)+'</li>' for p,t in downloads)+'</ul><p>'+link('../ph_fullrange_overnight/index.html','Original 96-level PH gallery')+' · '+link('figures/depth_profiles.png','Main depth chart')+' · '+link('comparisons/adjacent_changes.png','Adjacent-layer transitions')+' · '+link('h0_groups/h0_selected_threshold_profiles.png','Selected connectivity profiles')+'</p>')

style='''*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:#f5f7fa;color:#192a3b;font:17px/1.65 system-ui,-apple-system,sans-serif}header{background:#122d3c;color:#fff;padding:50px max(28px,calc((100vw - 1180px)/2)) 32px}header p{color:#cbd9e4;max-width:850px}header h1{font-size:42px;line-height:1.15;max-width:1000px;margin:12px 0}.eyebrow{text-transform:uppercase;font-size:13px;letter-spacing:.14em;color:#9edcca}nav{display:flex;flex-wrap:wrap;gap:12px 24px;padding-top:20px}nav a{color:#aee5d5}main{max-width:1240px;margin:auto;padding:12px 28px 70px}section{padding:28px 0;border-bottom:1px solid #d9e2e9;scroll-margin-top:12px}h2{font-size:29px;line-height:1.3;margin-top:0}h3{font-size:21px;line-height:1.35}p{max-width:1080px}a{color:#136858;text-underline-offset:3px}.lead{font-size:22px;line-height:1.5}.note{background:#fff2d7;border-left:4px solid #d8952e;padding:18px 22px}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:18px}article{background:#fff;border:1px solid #dde5eb;border-radius:12px;padding:22px}article h3{margin:8px 0}article p{font-size:16px;margin-bottom:0}.tag{color:#476578;font-size:12px;text-transform:uppercase;letter-spacing:.08em}.table-wrap{overflow:auto;background:#fff;border:1px solid #dce4ea;border-radius:9px;margin:22px 0}table{width:100%;border-collapse:collapse;font-size:15px}th,td{padding:13px 15px;border-bottom:1px solid #e4e9ed;text-align:left;vertical-align:top}th{background:#e9eff3;color:#243d4f;font-weight:650}tr:last-child td{border-bottom:0}td:first-child{font-weight:600}figure{margin:28px 0;background:white;padding:12px;border:1px solid #dce4ea;border-radius:10px}figure img{width:100%;height:auto;display:block}figcaption{font-size:14px;color:#526b7d;padding:12px 7px 0}.layer{background:#fff;border:1px solid #dce4ea;border-radius:8px;margin:9px 0;padding:15px 19px}.layer summary{cursor:pointer;font-weight:650}.layer small{display:block;color:#526b7d;font-weight:400;margin-top:5px}.layer p{font-size:16px}.badges{font-size:12px;color:#146958;padding-left:10px}.filters{display:flex;align-items:center;gap:18px;flex-wrap:wrap;margin:20px 0;padding:18px;background:#e9eff3;border-radius:9px}label{font-size:15px}select,input{font:inherit;padding:8px;border:1px solid #b5c7d3;border-radius:5px;background:white}#visible{font-size:14px;color:#526b7d}footer{max-width:1180px;margin:0 auto;padding:20px 28px;font-size:14px;color:#526b7d}@media(max-width:700px){body{font-size:16px}header{padding:30px 22px}header h1{font-size:31px}main{padding:12px 18px}h2{font-size:25px}.lead{font-size:19px}th,td{padding:10px}select,input{max-width:100%}}@media print{header{color:black;background:white}nav,.filters{display:none}details{break-inside:avoid}section{break-before:auto}figure{break-inside:avoid}}'''
html='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>What the PH results show · Crystal, StarCoder & OpenLLaMA</title><style>'+style+'</style></head><body><header><div class="eyebrow">Numerical representations · research analysis · 20 September 2026</div><h1>What the persistent homology results show</h1><p>What we examined, what we found, and which conclusions the evidence supports. Three models · 94 contextual layers · all 10,000 targets per layer.</p><nav><a href="#start">Main findings</a><a href="#checks">All 26 checks</a><a href="#atlas">Every layer</a><a href="#embedding">Embedding supplement</a><a href="#limits">Limits & next tests</a><a href="#data">Download data</a></nav></header><main>'+''.join(sections)+'</main><footer>Analysis uses saved geometry; no new model inference or Modal compute. Historical outputs preserved.</footer><script>function filter(){const model=document.getElementById("model").value,q=document.getElementById("search").value.toLowerCase().trim();let n=0;document.querySelectorAll(".layer").forEach(e=>{const show=(model==="all"||e.dataset.model===model)&&e.dataset.search.toLowerCase().includes(q);e.hidden=!show;if(show)n++});document.getElementById("visible").textContent=n+" layers"}document.getElementById("model").addEventListener("change",filter);document.getElementById("search").addEventListener("input",filter)</script></body></html>'
(OUT/'index.html').write_text(html)
(OUT/'criteria_results.json').write_text(json.dumps([dict(number=i+1,criterion=t,finding=f,usefulness=u,report_anchor=a) for i,(t,f,u,a) in enumerate(checks)],indent=2))
# Keep the analysis programs alongside results for reproducibility, without modifying the experiment repo.
(OUT/'reproduce').mkdir(exist_ok=True)
for name in ['ph_analysis.py','ph_additional_checks.py','ph_compare.py','ph_h0_groups.py','build_ph_report.py']:
 p=ROOT/'work'/name
 if p.exists():shutil.copy2(p,OUT/'reproduce'/name)
print(OUT/'index.html')
