
const $=id=>document.getElementById(id);let M=null,requestId=0,cache=new Map();
const digitColors=['#333333','#1f77b4','#ff7f0e','#2ca02c','#d62728','#9467bd','#8c564b','#e377c2','#7f7f7f','#17becf'];
const start=new URLSearchParams(location.hash.slice(1));
function options(id,items,wanted){const e=$(id);e.replaceChildren();for(const [value,text] of items){const o=document.createElement('option');o.value=value;o.textContent=text;e.append(o)}if([...e.options].some(o=>o.value===String(wanted)))e.value=String(wanted)}
function unique(values){return [...new Set(values)]}
function modelChange(){const gs=M.groups.filter(g=>g.model===$('model').value);options('task',gs.filter((g,i)=>gs.findIndex(h=>h.task===g.task)===i).map(g=>[g.task,g.task_name]),$('task').value||start.get('task'));taskChange()}
function taskChange(){const gs=M.groups.filter(g=>g.model===$('model').value&&g.task===$('task').value);options('context',gs.map(g=>[g.context_id,'Context '+g.context_id]),$('context').value||start.get('context'));contextChange()}
function group(){return M.groups.find(g=>g.model===$('model').value&&g.task===$('task').value&&g.context_id===$('context').value)}
function contextChange(){const g=group();options('layer',g?g.layers.map(l=>[String(l.layer),l.layer===0?'0 · input embedding':String(l.layer)]):[],$('layer').value||start.get('layer'));render()}
function empty(text){$('empty').textContent=text;$('empty').classList.remove('hidden')}
function addLink(text,url){const a=document.createElement('a');a.href=url;a.textContent=text;a.target='_blank';a.rel='noopener';if($('links').childNodes.length)$('links').append(' · ');$('links').append(a)}
async function render(){const mine=++requestId,g=group();for(const id of ['figure','plot','empty','colors'])$(id).classList.add('hidden');$('links').replaceChildren();if(!g){empty('No completed analysis groups are available yet. The pilot table remains in the results inventory.');return}
 const l=g.layers.find(l=>l.layer===Number($('layer').value)),view=$('view').value,b=g.behavior;
 $('behavior').className=b&&b.exact_accuracy>=.8?'good':'warn';$('behavior').textContent=b?`Pilot: ${b.correct}/${b.n} exact answers (${(100*b.exact_accuracy).toFixed(1)}%). ${b.warning||'Expected-answer colors still describe the requested answer, not each generated answer.'}`:'Pilot accuracy is unavailable. Do not interpret expected-answer coloring as task success.';
 let ev=l.explained_variance_ratio;let text=`${g.point_count.toLocaleString()} points · one task/context · saved level ${l.layer}. `;
 if(l.status==='valid')text+=`PCA variance: 2D ${(100*(ev[0]+ev[1])).toFixed(1)}%; 3D ${(100*ev.reduce((a,b)=>a+b,0)).toFixed(1)}%. `;else text+='Constant or numerically degenerate cloud: geometry unavailable. ';
 if(l.ph.status==='complete')text+=`At normalized connection distance 1: β₀=${l.ph.betti_at_one[0]}, β₁=${l.ph.betti_at_one[1]}.`;
 $('details').textContent=text;addLink('Group metrics',g.summary);addLink('Original saved arrays',l.arrays);
 history.replaceState(null,'','#'+new URLSearchParams({model:g.model,task:g.task,context:g.context_id,layer:l.layer,view}).toString());
 if(view.startsWith('comparison')){const family=g.task.endsWith('4')?'permutations':'notation',c=M.comparisons.find(c=>c.model===g.model&&c.context_id===g.context_id&&c.family===family&&c.layer===l.layer);const color=view==='comparison_input'?'input':'output';if(!c||!c.figures[color]){empty('This shared-coordinate comparison is not available. Written-number comparison uses underlying input-value colors.');return}showImage(c.figures[color]);$('details').textContent=`Shared PCA fit across ${c.tasks.length} matched conditions, ${c.point_count.toLocaleString()} targets per condition. Same axes and scale in every panel. Joint 2D explained variance: ${(100*(c.explained_variance_ratio[0]+c.explained_variance_ratio[1])).toFixed(1)}%.`;
 const low=M.groups.filter(x=>x.model===g.model&&x.context_id===g.context_id&&c.tasks.includes(x.task)&&(!x.behavior||x.behavior.exact_accuracy<.8)).map(x=>x.task_name);if(low.length){$('behavior').className='warn';$('behavior').textContent='Comparison includes absent or below-80% pilot accuracy: '+low.join(', ')+'. These shapes cannot establish successful transformation.'}addLink('Matched comparison arrays',c.arrays);return}
 if(view!=='3d'){if(l.figures[view])showImage(l.figures[view]);else empty('This figure is unavailable for the selected level. Constant clouds do not have informative PCA, kNN or PH.');return}
 if(!l.data3d){empty('No valid 3D projection for this constant or degenerate level.');return}
 $('colors').classList.remove('hidden');$('plot').classList.remove('hidden');
 try{let data=cache.get(l.data3d);if(!data){const response=await fetch(l.data3d);if(!response.ok)throw Error(response.status);data=await response.json();cache.set(l.data3d,data);if(cache.size>8)cache.delete(cache.keys().next().value)}if(mine!==requestId)return;plot3d(data,g,l)}catch(e){$('plot').classList.add('hidden');empty('Could not load saved 3D data: '+e.message)}
}
function showImage(path){$('figure').src=path;$('figure').classList.remove('hidden');addLink('Open full-size figure',path)}
function plot3d(d,g,l){const key=$('color').value,values=d[key],traces=[];const make=(indices,label,color)=>({type:'scatter3d',mode:'markers',name:label,x:indices.map(i=>d.scores[i][0]),y:indices.map(i=>d.scores[i][1]),z:indices.map(i=>d.scores[i][2]),customdata:indices.map(i=>[d.targets[i],d.input_text[i],d.expected_output[i],d.token_counts[i]]),hovertemplate:'Target %{customdata[0]}<br>Input: %{customdata[1]}<br>Expected: %{customdata[2]}<br>Prompt tokens: %{customdata[3]}<extra>%{fullData.name}</extra>',marker:{size:3,opacity:.72,color}});
 if(key==='token_counts'){const t=make(d.targets.map((_,i)=>i),'Prompt tokens',values);t.marker.colorscale='Viridis';t.marker.showscale=true;t.marker.colorbar={title:'Tokens'};traces.push(t)}else{const labels=unique(values).sort((a,b)=>String(a).localeCompare(String(b),undefined,{numeric:true}));labels.forEach((label,j)=>{const indices=values.map((v,i)=>v===label?i:-1).filter(i=>i>=0);const color=/^[0-9]$/.test(String(label))?digitColors[Number(label)]:`hsl(${(j*137.508)%360},65%,45%)`;traces.push(make(indices,String(label),color))})}
 const ev=d.explained_variance_ratio;Plotly.react('plot',traces,{margin:{l:0,r:0,t:38,b:0},title:{text:`${g.task_name} · ${g.model} · level ${l.layer}`,font:{size:17}},scene:{xaxis:{title:`PC1 (${(100*ev[0]).toFixed(1)}%)`},yaxis:{title:`PC2 (${(100*ev[1]).toFixed(1)}%)`},zaxis:{title:`PC3 (${(100*ev[2]).toFixed(1)}%)`},aspectmode:'data'},legend:{itemsizing:'constant'},uirevision:`${g.model}/${g.task}/${g.context_id}/${l.layer}`,paper_bgcolor:'white'},{responsive:true,displaylogo:false});
}
function shift(step){const e=$('layer');if(!e.options.length)return;e.selectedIndex=Math.max(0,Math.min(e.options.length-1,e.selectedIndex+step));render()}
$('model').onchange=modelChange;$('task').onchange=taskChange;$('context').onchange=contextChange;$('layer').onchange=render;$('view').onchange=render;$('color').onchange=render;$('prev').onclick=()=>shift(-1);$('next').onclick=()=>shift(1);
fetch('gallery/manifest.json').then(r=>{if(!r.ok)throw Error(r.status);return r.json()}).then(m=>{M=m;$('status').textContent=`${m.completed_groups}/${m.expected_groups} saved groups · ${m.figure_count.toLocaleString()} layer figures · ${m.three_d_view_count.toLocaleString()} 3D views · ${m.status.toUpperCase()}`;if(m.status!=='complete'){$('notice').textContent=`Partial export: ${m.missing_groups.length} groups absent or incomplete; ${m.missing_levels.length} groups have incomplete depth coverage; ${m.completed_comparison_levels}/${m.expected_comparison_levels} shared-comparison levels saved. Available completed summaries are selectable.`;$('notice').classList.remove('hidden')}for(const text of m.limitations){const li=document.createElement('li');li.textContent=text;$('limits').append(li)}options('model',unique(m.groups.map(g=>g.model)).map(x=>[x,x]),start.get('model'));if(start.has('view'))$('view').value=start.get('view');modelChange()}).catch(e=>{$('status').textContent='Gallery could not load.';empty('Serve this folder using a local HTTP server, then open index.html. Details: '+e.message)});
