
const $=id=>document.getElementById(id), controls=['group','model','task','context','layer'];
const names={original:'Original · 10,000 numbers',new:'New tasks · 1,000 targets',overlay:'Shared task comparisons',crystal:'Crystal',starcoder:'StarCoderBase-3B',openllama:'OpenLLaMA-3B',original_copy:'Original number copying',copy4:'Copy four digits',reverse4:'Reverse four digits',swap_first4:'Swap first two digits',swap_last4:'Swap last two digits',numeric_copy:'Copy 1–1,000 as digits',word_copy:'Copy 1–1,000 as words',permutations:'Four digit-transformation tasks',notation:'Digits and written words'};
const familyNames={polyhedron_vertices:'Polyhedron vertices',polyhedron_edges:'Polyhedron frames',polyhedron_surface:'Polyhedron surfaces',line:'Straight line',circle:'Circle',disk:'Disk',sphere:'Sphere',cylinder:'Cylinder surface',cone:'Cone surface',torus:'Torus surface',helix:'Open helix'};
const colors=['#547da5','#e99848','#59a85c','#cf5557','#8c6bb0','#997261','#cf83bc','#888888','#b0ad52'];
let manifest,templates,entry,fit,data,selected,revision=0;
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const val=(e,key)=>e[key]===null?'none':String(e[key]);
const pretty=x=>x.replaceAll('_',' ').replace('pitch','pitch ').replace(/r(0\.)/,'tube $1');
const num=x=>Number.isFinite(x)?x.toFixed(3):'—';
async function json(url){const r=await fetch(url);if(!r.ok)throw Error(url+': HTTP '+r.status);return r.json()}
function optionLabel(key,v){if(key==='context')return v==='none'?'Original context':'Context '+v;if(key==='layer')return 'Layer '+v;return names[v]||v}
function filterThrough(level){return manifest.entries.filter(e=>controls.slice(0,level).every(key=>val(e,key)===$(key).value))}
function populate(start=0,wanted={}){
 for(let i=start;i<controls.length;i++){const key=controls[i],previous=wanted[key]===undefined?$(key).value:String(wanted[key]===null?'none':wanted[key]);let values=[...new Set(filterThrough(i).map(e=>val(e,key)))];if(key==='layer')values.sort((a,b)=>Number(a)-Number(b));else if(key==='group')values.sort((a,b)=>['original','new','overlay'].indexOf(a)-['original','new','overlay'].indexOf(b));else values.sort();$(key).innerHTML=values.map(v=>`<option value="${esc(v)}">${esc(optionLabel(key,v))}</option>`).join('');if(values.includes(previous))$(key).value=previous;}
}
function resolve(){return filterThrough(controls.length)[0]}
function setHash(){if(!entry)return;history.replaceState(null,'','#id='+encodeURIComponent(entry.id)+(selected?'&shape='+encodeURIComponent(selected):''))}
async function loadEntry(desiredCandidate){
 const token=++revision;entry=resolve();if(!entry)return;fit=null;data=null;selected=null;$('identity').textContent=entry.id;$('direct').value=entry.id;$('error').textContent='';$('plot').innerHTML='<div class="noresult">Loading saved coordinates…</div>';
 try{const results=await Promise.all([json(entry.fit_url),entry.data_url?json(entry.data_url):Promise.resolve(null)]);if(token!==revision)return;[fit,data]=results;
 const layerOptions=[...$('layer').options];$('previous').disabled=$('layer').selectedIndex===0;$('next').disabled=$('layer').selectedIndex===layerOptions.length-1;
 $('flags').innerHTML=[entry.positional?'Positional embedding':null,entry.group==='overlay'?'Reused observations':null,entry.layer===0?'Input embedding level':null].filter(Boolean).map(t=>`<span class="flag">${t}</span>`).join('');
 $('links').innerHTML=`<a href="${esc(entry.fit_url)}">All fit measurements</a><a href="${esc(entry.source_url)}">Original PCA arrays</a>`;
 if(!data||!fit.fits){$('candidate').innerHTML='<option>No informative shape</option>';$('candidate').disabled=true;$('status').className='status';$('status').textContent='Constant cloud: no geometric shape can be meaningfully fitted.';$('metrics').innerHTML='';$('detail').textContent='The saved points coincide. This is recorded as a degenerate layer, not silently omitted.';$('projection').textContent='';$('ranking').innerHTML='No fit measurements.';$('sample').textContent='';$('plot').innerHTML='<div class="noresult">All saved coordinates coincide.<br>No meaningful shape comparison.</div>';setHash();return;}
 $('candidate').disabled=false;let options='';for(const family of [...new Set(templates.map(t=>t.family))]){options+=`<optgroup label="${esc(familyNames[family]||family)}">`;for(const t of templates.filter(t=>t.family===family))options+=`<option value="${esc(t.name)}">${esc(pretty(t.name))}</option>`;options+='</optgroup>'}$('candidate').innerHTML=options;
 selected=fit.fits.some(f=>f.name===desiredCandidate)?desiredCandidate:fit.fits[0].name;$('candidate').value=selected;$('plot').innerHTML='';render(true);
 }catch(e){if(token===revision)$('error').textContent='Unable to load this analysis: '+e.message}
}
function render(reset=false){
 if(!data||!fit)return;selected=$('candidate').value;const f=fit.fits.find(f=>f.name===selected),template=templates.find(t=>t.name===selected);setHash();
 $('status').className='status'+(f.screen_pass?' pass':'');$('status').innerHTML=f.screen_pass?'<strong>Passes the descriptive fit screen.</strong><br>This remains a candidate resemblance, not an identified topology.':'<strong>Does not pass the match screen.</strong><br>This candidate leaves too much mismatch, missing coverage, or a scale-bound issue.';
 const evr=entry.evr.reduce((a,b)=>a+b,0);$('metrics').innerHTML=[['Data residual',num(f.data_rms)],['Coverage residual',num(f.coverage_rms)],['Combined residual',num(f.symmetric_rms)],['Variance in 3 PCs',(100*evr).toFixed(1)+'%']].map(([label,value])=>`<div class="stat"><b>${value}</b><span>${label}</span></div>`).join('');
 const matches=fit.screen_matches||[];let detail=`95% of held-out points are within <b>${num(f.data_p95)}</b> radius units of this template. 95% of template points are within <b>${num(f.coverage_p95)}</b> of the held-out cloud.<br><br><b>${matches.length}</b> of 32 candidates pass the descriptive screen. Lowest combined residual: <b>${esc(pretty(fit.fits[0].name))}</b>.`;
 if(entry.positional)detail+='<p><strong>Position warning:</strong> this embedding-level arrangement can reflect token position, not learned numerical meaning.</p>';
 if(entry.group==='overlay')detail+='<p>This view combines tasks in one PCA basis; task offsets can create apparent structure.</p>';
 if(/reverse|swap|permutations/.test(entry.task))detail+='<p>Transformation accuracy varied by model. A shape here does not establish that the requested rule was executed correctly.</p>';
 $('detail').innerHTML=detail;
 let projection='';const p=fit.projection||{};if(p.neighbor4_retention3d!==undefined)projection='Only '+(100*p.neighbor4_retention3d).toFixed(1)+'% of original-space 4-neighbor links are retained in this 3D projection.';else if(p.distance_spearman!==undefined&&p.distance_spearman!==null)projection='Correlation with saved full-space pair-distance ranks: '+num(p.distance_spearman)+' (512 sampled pairs).';else projection='Full-space projection check: '+(p.reason||'not available')+'.';$('projection').textContent=projection;
 $('sample').textContent=`Showing ${data.displayed_count.toLocaleString()} of ${data.point_count.toLocaleString()} observations. Pose fitted on ${fit.train_count} training points; scores evaluated on ${fit.test_count.toLocaleString()} held-out points. Colors show ${entry.group==='overlay'?'tasks':'the input’s leading digit'}.`;
 $('ranking').innerHTML='<table><thead><tr><th>Candidate</th><th>Data residual</th><th>Coverage</th><th>Combined</th><th>Screen</th></tr></thead><tbody>'+fit.fits.map(x=>`<tr data-shape="${esc(x.name)}" class="${x.name===selected?'chosen':''}"><td>${esc(pretty(x.name))}</td><td>${num(x.data_rms)}</td><td>${num(x.coverage_rms)}</td><td>${num(x.symmetric_rms)}</td><td>${x.screen_pass?'Pass':'No match'}</td></tr>`).join('')+'</tbody></table>';
 for(const row of $('ranking').querySelectorAll('tr[data-shape]'))row.onclick=()=>{$('candidate').value=row.dataset.shape;render()};
 const traces=[];if($('showdata').checked){for(const label of [...new Set(data.labels)].sort((a,b)=>a-b)){const ids=data.labels.map((v,i)=>v===label?i:-1).filter(i=>i>=0);const labelName=entry.group==='overlay'?(names[entry.task_names[label-1]]||entry.task_names[label-1]):'Starts with '+label;traces.push({type:'scatter3d',mode:'markers',name:labelName,x:ids.map(i=>data.coordinates[i][0]),y:ids.map(i=>data.coordinates[i][1]),z:ids.map(i=>data.coordinates[i][2]),customdata:ids.map(i=>data.targets[i]),marker:{size:2.5,opacity:.55,color:colors[(label-1)%colors.length]},hovertemplate:esc(labelName)+'<br>Target %{customdata}<extra></extra>'})}}
 const points=template.points.map(v=>[0,1,2].map(j=>f.scale*(v[0]*f.rotation[0][j]+v[1]*f.rotation[1][j]+v[2]*f.rotation[2][j])+f.offset[j]));if($('showshape').checked){const curve=['line','circle','helix'].includes(template.family);let p=points;if(template.family==='circle')p=[...points,points[0]];traces.push({type:'scatter3d',mode:curve?'lines':'markers',name:'Fitted '+pretty(f.name),x:p.map(v=>v[0]),y:p.map(v=>v[1]),z:p.map(v=>v[2]),line:{color:'#121824',width:6},marker:{size:template.dimension===0?7:3,color:'#121824',opacity:.8,symbol:'diamond'},hovertemplate:'Fitted '+esc(pretty(f.name))+'<extra></extra>'})}
 const bounds=[...data.coordinates,...points];const mins=[0,1,2].map(j=>Math.min(...bounds.map(p=>p[j]))),maxs=[0,1,2].map(j=>Math.max(...bounds.map(p=>p[j])));const center=mins.map((v,j)=>(v+maxs[j])/2),half=Math.max(...maxs.map((v,j)=>(v-mins[j])/2))*1.07||1;const axis=j=>({title:'Normalized axis '+(j+1),range:[center[j]-half,center[j]+half],gridcolor:'#e1e5ed',zerolinecolor:'#bcc7d6',backgroundcolor:'#fcfdff'});
 const layout={margin:{l:0,r:0,t:6,b:0},paper_bgcolor:'white',font:{family:'system-ui',size:11,color:'#43516a'},legend:{orientation:'h',y:-.03},scene:{xaxis:axis(0),yaxis:axis(1),zaxis:axis(2),aspectmode:'cube',camera:{eye:{x:1.5,y:1.5,z:1.1}}},uirevision:reset?entry.id+'-'+Date.now():entry.id};if(!reset&&$('plot').layout?.scene?.camera)layout.scene.camera=$('plot').layout.scene.camera;Plotly.react('plot',traces,layout,{responsive:true,displaylogo:false,modeBarButtonsToRemove:['toImage']});
}
controls.forEach((key,index)=>$(key).onchange=()=>{populate(index+1);loadEntry()});$('candidate').onchange=()=>render();$('showdata').onchange=()=>render();$('showshape').onchange=()=>render();$('resetcamera').onclick=()=>render(true);
for(const [button,delta] of [['previous',-1],['next',1]])$(button).onclick=()=>{const layer=$('layer');layer.selectedIndex+=delta;loadEntry()};
$('openid').onclick=()=>{const e=manifest.entries.find(e=>e.id===$('direct').value.trim());if(!e){$('error').textContent='No saved cloud has that identifier.';return}populate(0,e);loadEntry()};
window.addEventListener('hashchange',()=>{const p=new URLSearchParams(location.hash.slice(1)),e=manifest.entries.find(e=>e.id===p.get('id'));if(e){populate(0,e);loadEntry(p.get('shape'))}});
(async()=>{try{[manifest,templates]=await Promise.all([json('manifest.json'),json('alltemplates.json')]);$('totals').textContent=`${manifest.counts.total.toLocaleString()} saved views indexed · ${manifest.counts.drawable.toLocaleString()} nonconstant clouds · 32 candidate shapes. Multiple views of the same observations are not independent replications.`;const p=new URLSearchParams(location.hash.slice(1));let e=manifest.entries.find(e=>e.id===p.get('id'))||manifest.entries.find(e=>e.id==='original_crystal_L07')||manifest.entries.find(e=>e.data_url)||manifest.entries[0];if(!e)throw Error('No completed fits yet');populate(0,e);await loadEntry(p.get('shape'))}catch(e){$('error').textContent=e.message}})();
